/**
 * Top-Level City Pages (Tier-2 und Tier-3).
 * Schreibstil: literarisch-editorial, Sie-Anrede.
 * Keyword-Dichte 1,5-2,5%, Location-spezifischer Content.
 */

import type { FAQ, Section } from './tier1-content'

export type CityMeta = {
  slug: string // top-level slug, z.B. 'fotograf-bonn'
  h1: string
  title: string
  description: string
  eyebrow: string
  city: string // human name, e.g. 'Bonn'
  tier: 2 | 3
  targetVolume: number // approximate search volume
}

export type CityPageContent = {
  meta: CityMeta
  intro: string[]
  sections: Section[]
  locations?: { name: string; note: string }[]
  faqs: FAQ[]
  closing: string
  relatedSlugs: string[] // 3 related tier-1 or city slugs
  pricing?: { name: string; price: string; note?: string }[]
}

export const cityPages: Record<string, CityPageContent> = {
  'fotograf-bonn': {
    meta: {
      slug: 'fotograf-bonn',
      h1: 'Fotograf in Bonn — Hochzeit, Portrait, Business',
      title: 'Fotograf Bonn | Lichtraum — Hochzeiten, Bewerbungsfotos, Portraits',
      description: 'Fotograf in Bonn und Umgebung: Hochzeiten im Poppelsdorfer Schloss, Bewerbungsfotos, Business-Portraits, Familien-Shoots. Basis in Euskirchen, ohne Anfahrts-Aufschlag bis Bonn.',
      eyebrow: 'Fotografie · Bonn & Rhein-Sieg',
      city: 'Bonn',
      tier: 2,
      targetVolume: 250,
    },
    intro: [
      'Bonn wird in der Fotograf-Suche oft unterschätzt — weil Google zuerst Köln anzeigt, weil viele Fotograf:innen aus Köln „nach Bonn mitkommen", aber die Stadt selten ernst nehmen. Das ist ein Fehler. Bonn hat die Kirschblütenallee, die Rheinaue, das Poppelsdorfer Schloss, die Drachenburg — und eine Lichtqualität, die im Rheinland einzigartig ist: das Siebengebirge spiegelt den Rhein auf besondere Weise, die Luft ist klarer als flussabwärts in Köln.',
      'Als Fotograf in Bonn arbeiten wir aus Euskirchen — 45 Minuten Anfahrt über die A61 oder die L162. Das ist keine große Distanz, und sie erlaubt uns, Bonn mit dem Blick zu fotografieren, den Einheimische oft verloren haben: als Stadt mit Charakter, nicht als „Köln-Ersatz". Wir fotografieren Hochzeiten, Portraits, Business-Shootings, Familienfotografie und Events im gesamten Bonner Stadtgebiet und im angrenzenden Rhein-Sieg-Kreis.',
    ],
    sections: [
      { h2: 'Was wir in Bonn fotografieren',
        body: [
          'Hochzeiten am Rhein, in Parks, in Schlössern. Die Kirschblütenallee zur Blütezeit (meist 10. bis 20. April) ist international bekannt und entsprechend fotografisch anspruchsvoll — wir kennen die weniger belagerten Abschnitte, die Tageszeiten mit wenig Tourismus und die besten Lichtfenster. Siehe dazu unsere spezialisierte Seite zum Hochzeitsfotograf Bonn.',
          'Business- und LinkedIn-Portraits für die starke UN-Stadt, die Bonner Behörden, die Deutsche Post DHL, die Telekom, die Universität und zahllose mittelständische Tech- und Beratungsfirmen. Wir kommen Onsite in Ihr Büro — innerhalb des Bonner Stadtgebiets ohne Zusatzkosten.',
          'Portraits, Paar- und Familien-Shoots in der Rheinaue, am Rheinufer, im Botanischen Garten Poppelsdorf oder auf den Venusbergen. Bonn hat eine auffällig hohe Dichte an fotogenen Parks und Gärten pro Quadratkilometer — für Shootings ein echter Vorteil.',
          'Event- und Pressefotografie bei Konferenzen, Gala-Abenden, Unternehmenseröffnungen — auf Tagessatzbasis, mit schneller Bild-Auslieferung für Pressemitteilungen.',
        ],
      },
      { h2: 'Warum wir auch in Bonn arbeiten, obwohl Köln näher liegt',
        body: [
          'Die meisten Bonner Fotograf:innen sitzen entweder in Köln (und „fahren mit runter") oder in Bonn selbst — und fotografieren die Stadt daher mit Lokalblick. Wir kommen als externe Beobachter aus der Eifel-Region: weit genug weg, um Bonn nicht als Alltag zu sehen, nah genug, um ohne Fahrtkostenpauschale zu kommen.',
          'Für viele Brautpaare aus Bonn ist das der Grund für die Zusammenarbeit. Ein Kölner Fotograf bringt Kölner Referenzen mit — das Brautpaar wünscht sich aber oft Bonn-Spezifika: den Kurfürstlichen Garten, die Drachenburg im Siebengebirge, die Godesburg. Wir haben diese Orte in unserem Repertoire und kennen die Eigenheiten jeder Location.',
          'Preislich liegen wir durch unseren Euskirchener Studio-Standort unter dem Kölner und Bonner Mittelwert. Nicht billig, aber 15 bis 25 Prozent unter vergleichbarem Niveau in den beiden Landeshauptstädten. Das kommt dem Endkunden direkt zugute.',
        ],
      },
      { h2: 'Bonner Locations — was funktioniert wann',
        body: [
          'Die Rheinaue ist das Bonner Shooting-Zentrum. Weitläufiger Park mit Seen, Brücken, Baumalleen — im Frühjahr und Herbst jeder Nachmittag ein Bildfestival. Im Sommer zu meiden bis 16 Uhr, dann zu voll. Morgens oder zur Golden Hour zwischen 18 und 20 Uhr ideal.',
          'Poppelsdorfer Schloss und Botanischer Garten sind das zweite Zentrum. Barocke Fassade, strukturierter Park, ruhige Wege — hervorragend für Paar-Shootings und Business-Environmental-Portraits. Der Botanische Garten hat moderate Eintrittspreise und ein genehmigungsbedürftiges Fotografier-Setup für gewerbliche Shootings, das wir vorab organisieren.',
          'Die Kirschblütenallee in der Heerstraße ist ikonisch — und entsprechend voll während der drei Blüten-Wochen im April. Wir fotografieren hier nur sehr früh morgens (6:30 bis 8:00 Uhr) oder abends nach 20 Uhr, wenn die Instagram-Touristen weg sind.',
          'Das Beethoven-Haus und die Bonner Altstadt liefern historischen Hintergrund, enge Gassen, gelbe Fassaden — ideal für Lifestyle- und Editorial-Portraits. Die Godesburg im Stadtteil Bad Godesberg eignet sich für dramatische Hochzeits- und Paar-Portraits mit Rheinblick.',
          'Drachenburg in Königswinter ist nicht mehr Bonn selbst (10 Min über die Konrad-Adenauer-Brücke), aber technisch in unserem kostenfreien Anfahrtsradius. Neugotisches Schloss, beste Golden-Hour-Spots im Rheinland.',
        ],
      },
      { h2: 'Preise und Leistungen im Überblick',
        body: [
          'Hochzeits-Reportagen in Bonn: ab 890 € (Standesamt) bis 2.790 € (Premium-Ganztag mit Zweitfotografin). Ausführlich auf unserer Seite zum Hochzeitsfotograf Bonn beschrieben.',
          'Portrait-Shootings in Bonn: ab 190 € für 45 Minuten Studio (Euskirchen) oder ab 390 € für On-Location in Bonn (90 Min, 20 bearbeitete Bilder).',
          'Business-/LinkedIn-Portraits: Einzel ab 190 €, Team ab 79 €/Person (Mindestmenge 3 Personen, Onsite in Bonn).',
          'Familien-Shootings im Bonner Stadtgebiet: ab 290 € für 90 Minuten.',
          'Anfahrt nach Bonn ist im Paketpreis enthalten. Keine versteckten Aufschläge, keine Kilometer-Pauschalen im Bonner und Rhein-Sieg-Bereich.',
        ],
      },
    ],
    locations: [
      { name: 'Rheinaue', note: 'weitläufiger Park mit Seen — perfekt für Golden-Hour-Shoots' },
      { name: 'Poppelsdorfer Schloss & Botanischer Garten', note: 'barock, strukturiert, ruhige Fotoumgebung' },
      { name: 'Kirschblütenallee (Heerstraße)', note: 'ikonisch im April — nur früh/spät besuchen' },
      { name: 'Beethoven-Haus & Altstadt', note: 'historischer Lifestyle-Hintergrund' },
      { name: 'Godesburg, Bad Godesberg', note: 'Rheinblick, dramatische Portraits' },
      { name: 'Drachenburg, Königswinter', note: '10 Min von Bonn — neugotisch, Golden Hour' },
    ],
    faqs: [
      { q: 'Fotografieren Sie auch in Bad Godesberg und Beuel?',
        a: 'Ja, beide Stadtteile zählen zu unserem kostenfreien Anfahrtsgebiet. In Bad Godesberg nutzen wir gerne die Godesburg, den Kurpark und die Kennedy-Brücke für Hochzeits-Portraits. In Beuel vor allem die Beueler Werft und die Pützchens Kirmes-Straßen für urbane Lifestyle-Shoots.' },
      { q: 'Kann ich Sie in die Rheinaue für ein Familienshooting buchen?',
        a: 'Sehr gerne. Die Rheinaue ist eine unserer Lieblings-Locations in Bonn. Wir treffen uns am Japanischen Garten, am Springbrunnen oder an der Auensee-Brücke — je nach Lichtverhältnis und Jahreszeit. 90-Minuten-Familien-Shoot für 290 €.' },
      { q: 'Arbeiten Sie mit Bonner Hochzeitsplaner:innen zusammen?',
        a: 'Ja, wir kennen mehrere der etablierten Bonner Wedding Planer aus gemeinsamen Projekten. Wenn Sie bereits mit einer Planerin zusammenarbeiten, sprechen Sie uns gerne an — die Chance ist hoch, dass wir uns schon begegnet sind oder dieselben Trauredner:innen kennen.' },
      { q: 'Wie lange braucht die Anfahrt von Euskirchen nach Bonn?',
        a: 'Von unserem Studio in Euskirchen etwa 40 bis 45 Minuten über die A61 und die B56, bei Stoßzeiten bis zu einer Stunde. Für Termine am frühen Morgen oder am späten Nachmittag rechnen wir mit 45 Min Fahrzeit. Anfahrt ist im Pauschalpreis enthalten.' },
      { q: 'Gibt es Bonner Hochzeitslocations, die Sie besonders empfehlen?',
        a: 'Kurfürstliches Schloss (heute Universität) für klassisch-elegante Hochzeiten, die Redoute in Bad Godesberg für Gala-Hochzeiten mit Park, das Fruchtkontor in der Altstadt für urbane Events, das Petersberg Hotel für Premium-Hochzeiten mit Rheinblick. Für kleinere, intimere Hochzeiten ist die La Redoute ein Geheimtipp.' },
    ],
    closing: 'Schreiben Sie uns, was Sie in Bonn planen — wir melden uns binnen 24 Stunden mit einem passenden Vorschlag. Für Hochzeiten, Business-Shoots oder Personal Branding bringen wir lokale Kenntnisse und professionelle Technik mit, ohne die oft überhöhten Innenstadtpreise großer Bonner Studios weiterzugeben.',
    relatedSlugs: ['hochzeitsfotograf-bonn', 'fotograf-koeln', 'hochzeitsfotograf-nrw'],
  },

  'hochzeitsfotograf-bonn': {
    meta: {
      slug: 'hochzeitsfotograf-bonn',
      h1: 'Hochzeitsfotograf in Bonn — Rhein, Schlösser, Siebengebirge',
      title: 'Hochzeitsfotograf Bonn | Lichtraum — Reportage & Editorial',
      description: 'Hochzeitsfotograf Bonn: Rheinaue, Poppelsdorfer Schloss, Petersberg, Drachenburg. Ganztags-Reportagen ab 1.890 €, Editorial-Stil, 12 Monate Vorlauf empfohlen.',
      eyebrow: 'Hochzeitsreportage · Bonn & Siebengebirge',
      city: 'Bonn',
      tier: 2,
      targetVolume: 200,
    },
    intro: [
      'Eine Hochzeit in Bonn hat einen anderen Rhythmus als eine in Köln. Die Stadt ist kleiner, die Hochzeitslocations liegen dichter beieinander, der Rhein fließt ruhiger. Das bedeutet: die Reportage kann konzentrierter sein, weniger Fahrzeit zwischen Getting-Ready, Trauung, Portraits und Feier — und mehr Zeit für die Momente zwischen den Programmpunkten.',
      'Als Hochzeitsfotograf Bonn begleiten wir Paare seit Jahren durch ihre Hochzeiten im Stadtgebiet, im Rhein-Sieg-Kreis und im angrenzenden Siebengebirge. Reportage-Stil, editorial-orientierte Portraits, ohne aufgesetztes Posieren, mit kenntnisreicher Location-Planung.',
    ],
    sections: [
      { h2: 'Bonner Hochzeitslocations — die Top 7',
        body: [
          'Das Petersberg Hotel in Königswinter thront über dem Rhein und ist das Prestige-Ziel für größere Hochzeiten mit 80 bis 200 Gästen. Gruppenfoto auf der Terrasse mit Rheinblick, Zeremonie im Saal, Feier bis spät in die Nacht. Preislich im Premium-Segment (Saalmiete ab 5.500 €), aber das Licht und die Kulisse rechtfertigen es.',
          'Die Redoute in Bad Godesberg ist das klassische Bonner Gala-Ziel — ein historisches Palais mit weitem Park, perfekt für Hochzeiten im Stil des späten 19. Jahrhunderts. Für Paare, die ein wenig altmodische Eleganz mögen, unerreicht.',
          'Das Kurfürstliche Schloss (heute Universität Bonn) bietet standesamtliche Trauungen im Beethovensaal — 15 Minuten Gehweg von der Rheinpromenade und damit für anschließende Portraits ideal positioniert. Für kleinere Hochzeiten (bis 40 Gäste) sehr empfehlenswert.',
          'Schloss Drachenburg in Königswinter ist die romantischste Kulisse des Rheinlands. Neugotisch, Schlosspark, Rheinblick — wir fotografieren dort regelmäßig und kennen die besten Portrait-Spots zur Golden Hour. Die Zeremonie selbst ist auf Anfrage möglich.',
          'Gut Heckenhof in Rheinbach (20 Min westlich) ist ein unterschätztes Gut mit Schlosspark, für Hochzeiten bis 120 Gäste. Moderate Preise, herrlich-ländliche Atmosphäre, ideal für Paare aus Bonn, die „raus in die Natur" wollen.',
          'Die Beueler Werft am östlichen Rheinufer ist eine moderne Alternative — industrieller Charme, Rheinblick, nach Bonn-Stadt hinüber. Für Paare mit urbaner Ästhetik.',
          'La Redoute (im Bundesviertel) ist ein Geheimtipp für intime Hochzeiten bis 30 Gäste. Klassizistisches Palais, privat geführt, exzellente Gastronomie.',
        ],
      },
      { h2: 'Unsere Hochzeits-Pakete für Bonn',
        body: [
          'Standesamt-Reportage (3 Stunden): 890 €. Ideal für kleine Hochzeiten im Beethovensaal des Kurfürstlichen Schlosses oder im Standesamt Bad Godesberg. 100 bis 200 bearbeitete Bilder, Lieferung binnen 3 Wochen.',
          'Halbtag (6 Stunden): 1.490 €. Deckt Getting-Ready oder Zeremonie, Portraits und Beginn der Feier ab. Ideal für Hochzeiten, deren Hauptteil nicht länger als 6 Stunden dauert.',
          'Ganztag (10 Stunden): 1.890 €. Von Getting-Ready bis zum ersten Tanz. Beliebtestes Paket für Hochzeiten mit 40 bis 100 Gästen.',
          'Premium (12 Stunden + After-Wedding-Shooting): 2.790 €. Inklusive Zweitfotograf:in und einem separaten Portrait-Termin in den Wochen nach der Hochzeit — für stressfreie Portraits ohne Zeitdruck.',
          'Zweitfotograf: + 490 €. Empfohlen ab 80 Gästen oder bei getrennten Getting-Readys. Für Hochzeiten auf dem Petersberg oder in der Redoute praktisch unverzichtbar.',
          'Alle Pakete enthalten: Vorgespräch, Ablaufplan-Abstimmung, Reportage am Hochzeitstag, 400 bis 900 farbkorrigierte Bilder (je nach Paket), Online-Galerie für Gäste, digitaler USB-Stick.',
        ],
      },
      { h2: 'Ablauf — eine typische Bonner Hochzeit aus unserer Perspektive',
        body: [
          'Vier Wochen vor der Hochzeit: Planungsgespräch per Telefon oder vor Ort. Wir gehen den Zeitplan durch, klären kritische Momente (Einzugsmusik, Erstansprache, Ringtausch), besprechen Familienwünsche und Gruppenfoto-Listen. Bei Hochzeiten mit religiöser Zeremonie klären wir vorab mit dem Pfarrer, wo wir stehen dürfen.',
          'Am Hochzeitstag: wir kommen meist 15 Minuten vor dem angekündigten Getting-Ready-Start. Kleine Details — der Brautstrauß, die Ringe auf einem Tuch, die Schuhe, das Kleid am Bügel — sind die ersten Bilder. Dann folgt das Getting-Ready selbst, meist etwa 60 bis 90 Minuten.',
          'Auf dem Weg zur Zeremonie fahren wir bei Stadthochzeiten parallel zum Auto des Brautpaars, um einen Ankunftsmoment zu dokumentieren. Bei Land-Hochzeiten (Petersberg, Drachenburg, Rheinbach) sind wir bereits vor Ort und nehmen die Ankunft aus Sicht der Gäste auf.',
          'Zwischen Zeremonie und Feier entsteht unser 45-Minuten-Portrait-Slot. Meist am Rhein, auf Schlossterrassen oder in ruhigen Parkanlagen. Hier entstehen die Bilder, die später gerahmt werden.',
          'Die Feier selbst dokumentieren wir bis ins Abendlicht — Dinner, Speeches, erster Tanz, erste Stunden der Party. Bei Premium-Paketen bleiben wir bis nach dem Eröffnungstanz-Block; danach kommt die Nachtdokumentation, die meist ohnehin in Videoform besser funktioniert.',
        ],
      },
      { h2: 'Was eine Hochzeit in Bonn fotografisch besonders macht',
        body: [
          'Das Bonner Licht hat eine Eigenart, die Kölner Fotograf:innen oft nicht sofort erkennen: der Rhein ist hier breiter und ruhiger, die Reflexionen intensiver, die Luftschichtungen anders. Zur goldenen Stunde liegen Bonn und Siebengebirge in einem warm-violetten Dunst, der wie ein natürliches Weichzeichner-Filter wirkt.',
          'Für Hochzeiten bedeutet das: die „perfekte Lichtstunde" liegt in Bonn etwa 10 bis 15 Minuten später als in Köln. Wir planen Portrait-Sessions entsprechend — lieber etwas später starten, um das volle warme Spektrum zu erwischen.',
          'Ein weiterer Vorteil: Bonn hat weniger vertikale Architektur als Köln. Das bedeutet weniger harte Schlagschatten mittags, mehr offene Flächen für freie Kompositionen. Besonders in der Rheinaue und im Botanischen Garten liefert das bessere Portrait-Bedingungen als der Rheingarten in Köln.',
        ],
      },
    ],
    locations: [
      { name: 'Petersberg Hotel, Königswinter', note: 'Rheinblick, Terrasse — für große Gala-Hochzeiten' },
      { name: 'Redoute, Bad Godesberg', note: 'historisches Palais, für klassische Eleganz' },
      { name: 'Schloss Drachenburg', note: 'neugotisch, romantisch — beste Golden Hour' },
      { name: 'Kurfürstliches Schloss / Beethovensaal', note: 'standesamtlich, zentral, kleine Hochzeiten' },
      { name: 'Gut Heckenhof, Rheinbach', note: 'ländliches Gut, 120 Gäste möglich' },
      { name: 'La Redoute (Bundesviertel)', note: 'Geheimtipp, intim, bis 30 Gäste' },
      { name: 'Beueler Werft', note: 'industrieller Charme, urban' },
    ],
    pricing: [
      { name: 'Standesamt (3 h)', price: '890 €' },
      { name: 'Halbtag (6 h)', price: '1.490 €' },
      { name: 'Ganztag (10 h)', price: '1.890 €', note: 'Beliebtestes Paket' },
      { name: 'Premium (12 h + After-Wedding)', price: '2.790 €' },
      { name: 'Zweitfotograf', price: '+ 490 €' },
    ],
    faqs: [
      { q: 'Wie viel kostet ein Hochzeitsfotograf in Bonn?',
        a: 'Realistisch zwischen 1.500 € und 3.500 € für einen Ganztag. Wir liegen mit 1.890 € für 10 Stunden im oberen Mittelfeld — inklusive Retusche, Online-Galerie und digitalem USB-Stick. Paare, die das Premium-Paket mit Zweitfotograf und After-Wedding-Shoot wünschen, rechnen mit 2.790 € plus Anzahlung.' },
      { q: 'Kommen Sie auch zu unserer standesamtlichen Trauung?',
        a: 'Ja, sehr gerne. Das Bonner Standesamt im Kurfürstlichen Schloss und das Bad Godesberger Standesamt haben beide unterschiedliche Abläufe — wir kennen sie und wissen, wo wir als Fotograf:in stehen dürfen und wann der optimale Moment für den Ringtausch-Shot kommt.' },
      { q: 'Fotografieren Sie auch am Petersberg?',
        a: 'Ja, regelmäßig. Der Petersberg ist eine unserer Top-Locations für Gala-Hochzeiten. Wir haben eine kurze Arbeitsbeziehung mit dem Hauskoordinator und wissen, welche Räume sich für welche Shooting-Szenen eignen. Die Terrasse zur Golden Hour ist ein echtes Foto-Highlight.' },
      { q: 'Wie früh sollte ich für eine Hochzeit im Bonner Raum buchen?',
        a: 'Für Samstage zwischen Mai und September empfehlen wir 9 bis 12 Monate Vorlauf. Wegen der Petersberg-Hochzeiten (immer begehrte Termine) und der begrenzten Kapazität bei der Drachenburg raten wir eher zu 12 Monaten. Kurzfristige Termine in der Nebensaison (November bis März) sind oft noch möglich.' },
      { q: 'Bieten Sie After-Wedding-Shoots in Königswinter oder dem Siebengebirge an?',
        a: 'Sehr gerne. Der Drachenfels-Pfad, die Rheinaue und das Weinberge-Panorama bei Königswinter sind drei der schönsten After-Wedding-Kulissen im Rheinland. Ein separater Termin in den Wochen nach der Hochzeit gibt uns mehr Zeit für intimere Portraits ohne den Zeitdruck des eigentlichen Hochzeitstags.' },
    ],
    closing: 'Wenn Sie in Bonn heiraten und einen Fotografen suchen, der die Stadt, ihre Locations und ihre Lichtqualität wirklich kennt — schreiben Sie uns. Wir prüfen die Verfügbarkeit Ihres Datums und senden binnen 24 Stunden einen konkreten Vorschlag.',
    relatedSlugs: ['fotograf-bonn', 'hochzeitsfotograf-koeln', 'hochzeitsfotograf-nrw'],
  },

  'fotograf-leverkusen': {
    meta: {
      slug: 'fotograf-leverkusen',
      h1: 'Fotograf in Leverkusen — Schloss Morsbroich, Japanischer Garten, Neulandpark',
      title: 'Fotograf Leverkusen | Lichtraum — Portrait, Hochzeit, Business',
      description: 'Fotograf Leverkusen: Schloss Morsbroich, Neulandpark, Japanischer Garten. Portraits, Hochzeiten, Business-Shoots. Aus Euskirchen bis 55 km Anfahrt ohne Aufschlag.',
      eyebrow: 'Fotografie · Leverkusen & Bergisches Land',
      city: 'Leverkusen',
      tier: 2,
      targetVolume: 100,
    },
    intro: [
      'Leverkusen ist mehr als Bayer-Werk und BayArena. Drei der außergewöhnlichsten Foto-Kulissen im Rheinland liegen im Stadtgebiet: Schloss Morsbroich als Barockresidenz mit modernem Kunstmuseum, der Neulandpark als lebendige Freiflächen-Anlage am Rheinufer und der Japanische Garten als zeitgenössische Mini-Oase mit Teichen, Pavillons und präzise gesetzter Pflanzung.',
      'Als Fotograf in Leverkusen arbeiten wir aus Euskirchen. 55 Minuten Anfahrt über die A1 und die A59. Wir fotografieren Portraits, Paar-, Familien-, Business- und Hochzeits-Shoots im gesamten Leverkusener Stadtgebiet und im angrenzenden Bergischen Land.',
    ],
    sections: [
      { h2: 'Leverkusener Locations im Einzelnen',
        body: [
          'Schloss Morsbroich ist eines der bedeutendsten Barockresidenzen im Rheinland — heute mit integriertem Museum für zeitgenössische Kunst. Für Hochzeiten und edle Portraits liefert der Schlosspark, die südliche Fassade und die Orangerie drei sehr unterschiedliche Bildsprachen. Wir empfehlen Morsbroich besonders für Paare mit Sinn für historische Ästhetik und zeitgenössische Unruhe in einem.',
          'Der Neulandpark am Rheinufer wurde für die Landesgartenschau 2005 angelegt und ist heute einer der schönsten Stadtparks im Westen Deutschlands. Weite Rasenflächen, Seerosenteiche, alte Baumbestände, Brücken, Skulpturen, Aussichtspunkte mit Rheinblick. Familienshootings hier sind fast unschlagbar — Kinder können spielen, die Eltern in Ruhe atmen, und wir haben alle 500 Meter eine neue Bildgelegenheit.',
          'Der Japanische Garten im Carl-Duisberg-Park ist das foto-dichteste Stück Leverkusens. Zwei Hektar mit perfekt kuratiertem Garten-Design — Teehäuser, Wasserbecken, Brücken, Kirschbäume, Lampions. Im April (Kirschblüte) und Oktober (Herbstfärbung) fotografisch am spektakulärsten.',
          'Darüber hinaus arbeiten wir gerne im Carl-Duisberg-Park, in der Schlebuscher Altstadt (eine unterschätzte, gut erhaltene Fachwerkkulisse) und auf der Manforter Weide mit Rheinblick.',
        ],
      },
      { h2: 'Was wir in Leverkusen fotografieren',
        body: [
          'Portraits in allen Varianten: editorial, klassisch, Lifestyle, Personal Branding. Schloss Morsbroich und der Japanische Garten liefern dabei zwei sehr unterschiedliche Stimmungen, zwischen denen wir je nach gewünschter Bildsprache wechseln.',
          'Paar- und Verlobungsshootings im Neulandpark, an der Manforter Weide oder im Japanischen Garten zur Golden Hour. Die Mischung aus Kulturgarten und Rheinlandschaft ist in Leverkusen einzigartig.',
          'Hochzeiten im Schloss Morsbroich (für 40 bis 120 Gäste), auf Gut Schiff, im Schloss Morsbroich Hotel. Unser 10-Stunden-Ganztags-Paket (1.890 €) ist hier das üblichste gewählte Format.',
          'Business- und Personal-Branding-Portraits für Bayer-Mitarbeiter, Leverkusener Mittelständler, Handwerksbetriebe und Selbständige. Unsere 3-Stunden-Personal-Branding-Session mit 2 bis 3 Locations (Studio-Setting, outdoor im Park, optional Home/Office) für 890 € ist für Leverkusener Kunden eine häufige Buchung.',
          'Familien-Shoots im Neulandpark oder im Carl-Duisberg-Park, typischerweise 90 Minuten für 290 €, 30 bearbeitete Bilder.',
        ],
      },
      { h2: 'Was Leverkusener Shootings von Kölner unterscheidet',
        body: [
          'Leverkusen hat einen auffallend ruhigen Park-Charakter. Der Neulandpark wird an Wochenenden zwar gut besucht, aber nie so überlaufen wie der Kölner Stadtgarten oder die Rheinpromenade am Kölner Dom. Für Fotograf:innen heißt das: mehr Raum, weniger Touristen im Bildhintergrund, weniger Zeit, die man mit Warten auf freie Blicke verbringt.',
          'Die Leverkusener Kundschaft ist häufig technisch-industriell orientiert (Bayer, Chempark, Zulieferer) — und hat ein entsprechend spezifisches Bedürfnis an Business-Portraits: klar, sachlich, nicht übermäßig kreativ. Wir passen unseren Stil dem an, ohne die editorial-orientierte Bildqualität aufzugeben.',
          'Der Rhein ist bei Leverkusen ruhiger als in Köln oder Bonn — die Frachtschifffahrt verläuft weiter in der Flussmitte, die Uferwege sind seltener besucht. Das macht Golden-Hour-Shootings am Rheinufer besonders angenehm: wir arbeiten oft auf den letzten 30 Minuten vor Sonnenuntergang auf der Manforter Weide mit nur vereinzelten Spaziergängern im Hintergrund.',
          'Auch die Preisstruktur unterscheidet sich merklich: Leverkusener Studio-Mieten liegen etwa 30 Prozent unter Kölner Niveau, was sich in fairen Paketpreisen für unsere Kunden bemerkbar macht. Wir geben diese Kostenersparnis weiter, ohne an Qualität oder Technik zu sparen.',
        ],
      },
    ],
    locations: [
      { name: 'Schloss Morsbroich', note: 'Barockresidenz mit zeitgenössischem Museum' },
      { name: 'Neulandpark am Rheinufer', note: 'Landesgartenschau-Park, ideal für Familien' },
      { name: 'Japanischer Garten', note: 'Im April und Oktober spektakulär' },
      { name: 'Carl-Duisberg-Park', note: 'Stille Wege, Baumbestände' },
      { name: 'Manforter Weide', note: 'Rheinblick, Golden Hour' },
      { name: 'Schlebuscher Altstadt', note: 'Fachwerk, Lifestyle-Kulisse' },
    ],
    faqs: [
      { q: 'Fahren Sie wirklich von Euskirchen nach Leverkusen ohne Aufschlag?',
        a: 'Ja. Unsere 60-km-Regel (kostenfreie Anfahrt) deckt Leverkusen ab. Die Anfahrt dauert je nach Uhrzeit 55 bis 75 Minuten über A1 und A59. Wir rechnen sie in die Paketzeit ein.' },
      { q: 'Kann ich Schloss Morsbroich als Hochzeitslocation buchen?',
        a: 'Ja, das Schloss hat einen Hochzeits-Koordinator und mehrere Saal-Varianten. Kapazität bis etwa 120 Gäste. Wir fotografieren dort regelmäßig und kennen die besten Spots — die Orangerie, den Schlosspark hinter der Südseite, den Ehrenhof zur Golden Hour.' },
      { q: 'Wann ist der beste Zeitpunkt für ein Shooting im Japanischen Garten?',
        a: 'Kirschblüte im April (ca. 3 Wochen) und Herbstfärbung Mitte bis Ende Oktober. Im Sommer ist der Garten ruhiger, aber visuell weniger spektakulär. Winteraufnahmen (Reifschleier, stille Teiche) sind ein gut gehüteter Geheimtipp, weil kaum andere Fotografen dann dort sind.' },
      { q: 'Bieten Sie spezielle Bayer-Mitarbeiterpreise an?',
        a: 'Ja, für Gruppen-Anfragen ab 5 Personen aus einem Team (Bewerbungsfotos, LinkedIn-Portraits) machen wir ein Pauschal-Paket mit Rabatt. Bei Einzelbuchungen gelten reguläre Preise.' },
      { q: 'Kommen Sie auch in den Chempark für Onsite-Shoots?',
        a: 'Auf Anfrage ja. Onsite-Shoots in sicherheitsrelevanten Industrieumgebungen erfordern Vorab-Genehmigungen, die üblicherweise 2 bis 4 Wochen Vorlauf brauchen. Für Chempark-Anfragen direkt mit uns sprechen, wir kennen die Abläufe.' },
    ],
    closing: 'Schreiben Sie uns Ihren Anlass und Ihren Wunschort in Leverkusen — wir melden uns binnen 24 Stunden mit einem Location-Vorschlag und einem Kostenvoranschlag.',
    relatedSlugs: ['fotograf-koeln', 'fotograf-bonn', 'hochzeitsfotograf-koeln'],
  },

  'fotograf-siegburg': {
    meta: {
      slug: 'fotograf-siegburg',
      h1: 'Fotograf in Siegburg — Michaelsberg & Altstadt',
      title: 'Fotograf Siegburg | Lichtraum — Portrait, Hochzeit, Business',
      description: 'Fotograf Siegburg: Michaelsberg, Altstadt, Sieg-Ufer. Portraits, Hochzeiten, Business-Shoots. Aus Euskirchen mit kostenfreier Anfahrt.',
      eyebrow: 'Fotografie · Siegburg & Rhein-Sieg',
      city: 'Siegburg',
      tier: 3,
      targetVolume: 60,
    },
    intro: [
      'Siegburg zwischen Köln und Bonn hat eine der schönsten Aussichtslagen im Rheinland: den Michaelsberg mit Benediktinerkloster, der bei klarem Wetter bis zum Kölner Dom reicht. Die Siegburger Altstadt unten fügt historische Fachwerk-Kulissen hinzu, und die Sieg-Flussaue liefert Wasser und Bäume.',
      'Als Fotograf in Siegburg bedienen wir Portraits, Hochzeiten, Business- und Familienshootings. Die Anfahrt von Euskirchen dauert etwa 60 Minuten über die A560 — und ist im Pauschalpreis enthalten.',
    ],
    sections: [
      { h2: 'Die Siegburger Locations im Überblick',
        body: [
          'Der Michaelsberg ist für Hochzeiten und Paar-Portraits in der Region unerreicht. Die Terrasse vor der Klosterkirche bietet Panoramablick, die Klosteranlage selbst einen Innenhof mit romanischen Bögen, der Michaelsbergpfad führt durch Mischwald für intime Portrait-Momente.',
          'Die Siegburger Altstadt ist überraschend gut erhalten. Marktplatz, Rathaus, Holzgasse — enge mittelalterliche Wege mit Fachwerkhäusern. Für Lifestyle-Shootings und urbane Portraits mit historischem Hintergrund eine seltene Ressource in der Region.',
          'Das Sieg-Ufer unterhalb des Michaelsbergs bietet eine ruhige Flussszene mit Baumalleen und weitläufigen Wiesen. Hier fotografieren wir gerne Familien- und Paar-Shootings zur Golden Hour.',
        ],
      },
      { h2: 'Typische Anlässe in Siegburg',
        body: [
          'Hochzeiten am Michaelsberg (Trauung in der Klosterkirche, Portrait-Session auf der Terrasse, Feier in der Klosteranlage oder im nahen Hotel Kranz) sind eine feste Größe in unserem Jahreskalender. Kapazität etwa 60 bis 120 Gäste, perfekt für mittelgroße Hochzeiten mit spirituellem Ort-Bezug.',
          'Bewerbungs- und Business-Portraits für Siegburger Kunden entstehen typischerweise in unserem Studio in Euskirchen (30 Minuten westlich). Für Team-Shoots ab 3 Personen kommen wir auch nach Siegburg — beispielsweise in Kanzlei-Räume oder Agenturbüros.',
          'Familien-Shoots auf der Michaelsbergpfad-Route, am Sieg-Ufer oder im Siegburger Stadtpark. Kinder genießen die offene Natur, die Wege sind kinderwagentauglich.',
        ],
      },
      { h2: 'Was wir in Siegburg anders machen',
        body: [
          'Viele Fotograf:innen, die „nach Siegburg kommen", kennen die Stadt nur oberflächlich und fotografieren ausschließlich am Michaelsberg. Wir kennen alle drei großen Kulissen (Berg, Altstadt, Ufer) und kombinieren sie in größeren Shoots — der Vorteil: 90 Minuten Portrait-Session mit drei völlig unterschiedlichen Stimmungen, ohne mehr als 800 Meter zu Fuß gehen zu müssen.',
          'Der Michaelsberg hat eine Licht-Eigenart: morgens steht die Sonne hinter dem Kloster, mittags über der Altstadt, abends über der Sieg. Das bedeutet für Hochzeiten: die Trauung am Vormittag, Portraits am späten Nachmittag, Feier in der Dämmerung — ein natürlicher Rhythmus, den wir gern nutzen.',
        ],
      },
      { h2: 'Anfahrt und lokale Infrastruktur',
        body: [
          'Siegburg ist aus Euskirchen in etwa 55 bis 70 Minuten erreichbar, je nach Stoßzeit auf der A560 und der A3. Für Hochzeiten am Michaelsberg reservieren wir meist einen Hotel-Stellplatz in Siegburg, damit wir bei mehrtägigen Events die Anfahrt minimieren.',
          'Die Siegburger Infrastruktur für Hochzeiten ist vorbildlich. Hotel Kranz und Hotel Stern liegen im direkten Umkreis des Michaelsbergs, beide mit Shuttle-Service zur Klosteranlage. Für kleinere Feiern nutzen wir gerne die Altstadt-Restaurants (etwa das Brauhaus am Markt), für größere Bankette das Kranz-Hotel.',
        ],
      },
    ],
    locations: [
      { name: 'Michaelsberg Kloster', note: 'Panoramablick, Innenhof — ideal für Hochzeiten' },
      { name: 'Siegburger Altstadt', note: 'Fachwerk, Marktplatz, enge Gassen' },
      { name: 'Sieg-Ufer', note: 'Flussaue, weitläufige Wiesen, ruhig' },
      { name: 'Michaelsbergpfad', note: 'Mischwald zwischen Berg und Altstadt' },
    ],
    faqs: [
      { q: 'Kann man im Michaelsberg-Kloster heiraten?',
        a: 'Ja, die Klosterkirche hat standesamtliche und kirchliche Trauungen. Kapazität etwa 100 Gäste. Wir empfehlen eine Anfrage beim Kloster-Koordinator mindestens 12 Monate vor Wunschdatum, beliebte Samstagstermine sind weit im Voraus weg.' },
      { q: 'Wie lange dauert die Anfahrt nach Siegburg?',
        a: 'Von unserem Studio in Euskirchen etwa 55 bis 70 Minuten über A61 und A560. Im Paketpreis enthalten.' },
      { q: 'Gibt es Parkplätze am Michaelsberg?',
        a: 'Ja, direkt unterhalb der Klosteranlage ein größerer Parkplatz. Für Hochzeiten mit vielen Gästen empfehlen wir den Parkplatz am Bahnhof Siegburg und den Aufstieg per Fußweg (5 Minuten) — das schafft einen natürlichen „Ankunftsmoment", den wir gerne fotografieren.' },
      { q: 'Haben Sie Erfahrung mit katholischen Trauungen in Siegburg?',
        a: 'Ja. Das Michaelsberg-Kloster ist ein Benediktinerkloster mit eigenen liturgischen Abläufen. Wir kennen die Pfarrer und Organisten, wissen wo wir während der Messe stehen dürfen (Seiten-Emporen, hintere Reihen) und halten uns an die klaren Regeln — z. B. kein Fotografieren während der Wandlung.' },
    ],
    closing: 'Schreiben Sie uns Ihren Termin und Ihren Wunsch — für Siegburg bringen wir Orts- und Klosterkenntnis mit, die einem externen Kölner Fotografen oft fehlt.',
    relatedSlugs: ['hochzeitsfotograf-bonn', 'fotograf-bonn', 'fotograf-koeln'],
  },

  'fotograf-bergisch-gladbach': {
    meta: {
      slug: 'fotograf-bergisch-gladbach',
      h1: 'Fotograf in Bergisch Gladbach — Schloss Bensberg & Altstadt',
      title: 'Fotograf Bergisch Gladbach | Lichtraum — Schloss Bensberg, Portrait, Hochzeit',
      description: 'Fotograf Bergisch Gladbach: Schloss Bensberg, Altstadt, Strunder Bach. Hochzeiten, Portraits, Business-Shoots im Bergischen Land.',
      eyebrow: 'Fotografie · Bergisch Gladbach',
      city: 'Bergisch Gladbach',
      tier: 3,
      targetVolume: 60,
    },
    intro: [
      'Bergisch Gladbach verbindet urbanes Leben mit den Ausläufern des Bergischen Lands. Schloss Bensberg ist eine der prestigeträchtigsten Hochzeitslocations Deutschlands — ein Grandhotel auf einem Berghang mit Blick bis nach Köln. Die Bergisch Gladbacher Altstadt und der Strunder Bach runden das Foto-Repertoire ab.',
      'Als Fotograf in Bergisch Gladbach fotografieren wir Hochzeiten, Portraits und Business-Shoots. Die Anfahrt von Euskirchen dauert etwa 70 Minuten über A61, A4 und A3.',
    ],
    sections: [
      { h2: 'Schloss Bensberg — die Referenz-Hochzeitslocation',
        body: [
          'Schloss Bensberg ist eines der wenigen Grandhotels in Deutschland, das Hochzeits-Shootings zulässt — und das mit einer Kulisse, die international Maßstäbe setzt. Die Schlossterrasse mit Rheinblick, die marmorne Eingangshalle, der Barockgarten: jedes Element liefert anderen visuellen Wert.',
          'Wir fotografieren hier vor allem Halbtag- und Ganztags-Hochzeiten (1.490 € bis 1.890 €). Die Schlosskoordinator:innen sind fotografen-freundlich, die Genehmigung für gewerbliche Shootings dort ist Teil unserer Standard-Vorbereitung.',
          'Preis-Warnung: Schloss Bensberg selbst ist Premium-preis (Saalmiete ab 6.000 €, Catering oberste Klasse). Paare, die dort heiraten, suchen meist auch einen Premium-Fotografen — unser Ganztags-Paket mit Zweitfotograf für 2.380 € ist in diesem Kontext angemessen.',
        ],
      },
      { h2: 'Weitere Bergisch Gladbacher Kulissen',
        body: [
          'Die Bergisch Gladbacher Altstadt am Konrad-Adenauer-Platz bietet Fachwerk, Marktstimmung und historische Architektur. Ideal für Lifestyle-Shootings und urbane Paar-Portraits.',
          'Der Strunder Bach führt durch einen grünen Stadtkorridor zwischen Altstadt und Bergischem Land. Baumreihen, Brücken, stiller Bachlauf — ein natürlicher Studio-Raum für Familien-Shoots.',
          'Das Forum (Kulturzentrum) und das Unternehmen Zanders Park geben modernen architektonischen Hintergrund für Business- und Editorial-Portraits.',
        ],
      },
      { h2: 'Anfahrt, Übernachtung und Planungshinweise',
        body: [
          'Von Euskirchen fahren wir etwa 70 Minuten nach Bergisch Gladbach über die A61, die A4 und die A3 — die Anfahrt ist im Pauschalpreis enthalten. Bei Hochzeiten auf Schloss Bensberg empfehlen wir eine Übernachtung für uns vor Ort, damit wir morgens fit und pünktlich zum Getting-Ready erscheinen.',
          'Schloss Bensberg bietet neben den Hochzeitsräumen auch ein Grandhotel mit 120 Zimmern. Viele unserer Paare buchen für sich und enge Familienmitglieder die Bensberg-Suiten als vor-Hochzeits-Unterkunft.',
          'Für Business-Shootings in Bergisch Gladbach empfehlen wir Termine werktags zwischen 10 und 14 Uhr — das ist die Zeit, in der der Strunder Bach und die Altstadt am ruhigsten sind und wir die Motive ohne Passanten fotografieren können.',
        ],
      },
    ],
    locations: [
      { name: 'Schloss Bensberg', note: 'Grandhotel mit Rheinblick — Premium-Hochzeiten' },
      { name: 'Altstadt am Konrad-Adenauer-Platz', note: 'Fachwerk, historisch' },
      { name: 'Strunder Bach', note: 'Grüner Korridor, Familien-Shoots' },
      { name: 'Forum Bergisch Gladbach', note: 'moderne Architektur, Business-Shoots' },
    ],
    faqs: [
      { q: 'Ist Schloss Bensberg bei Ihnen buchbar?',
        a: 'Die Hochzeits-Kooperation mit Schloss Bensberg ist Teil unserer Standard-Arbeitsweise. Sobald Sie dort einen Termin gebucht haben, übernehmen wir die fotografische Genehmigung und Ablaufabstimmung.' },
      { q: 'Wie teuer ist eine Hochzeit in Schloss Bensberg inklusive Fotografie?',
        a: 'Als grobe Richtung: Saalmiete ab 6.000 €, Catering 150 bis 250 € pro Gast, Fotografie (unser Ganztags-Paket mit Zweitfotograf) 2.380 €. Gesamt für eine 80-Personen-Hochzeit etwa 22.000 bis 28.000 €.' },
      { q: 'Ist der Strunder Bach für Familien-Shoots geeignet?',
        a: 'Sehr. Wir fotografieren dort oft Familien mit Kindern, die Wege sind kinderwagentauglich, der Bach plätschert beruhigend. Lichtverhältnis weich dank Baumbestand.' },
      { q: 'Welche Hochzeitsgröße passt zu Schloss Bensberg?',
        a: 'Schloss Bensberg eignet sich für Hochzeiten von 60 bis 200 Gäste. Kleinere Hochzeiten wirken in den großzügigen Räumlichkeiten oft verloren. Für intime Mikro-Hochzeiten (unter 30 Gäste) empfehlen wir alternativ die Villa Zanders oder kleinere Kölner Locations.' },
      { q: 'Gibt es Fotografen-Einschränkungen auf Schloss Bensberg?',
        a: 'Im Innenbereich kein Blitzlicht, keine Drohnen ohne separate Genehmigung der Hotelverwaltung. Die Schlossterrasse zur goldenen Stunde ist frei zugänglich, aber bei anderen Hochzeiten am gleichen Tag kann es zu Terminüberschneidungen kommen — wir klären das vorab mit dem Bensberg-Koordinator.' },
    ],
    closing: 'Schreiben Sie uns — für Bergisch Gladbach bringen wir Schloss-Bensberg-Erfahrung und Kenntnis der weniger bekannten Stadtlocations mit. Auf Wunsch kommen wir vorab für ein kurzes Location-Scouting auf das Schlossgelände, um gemeinsam die besten Portrait-Spots zu markieren.',
    relatedSlugs: ['fotograf-koeln', 'hochzeitsfotograf-koeln', 'fotograf-leverkusen'],
  },

  'fotograf-erftstadt': {
    meta: {
      slug: 'fotograf-erftstadt',
      h1: 'Fotograf in Erftstadt — Schloss Gracht & Erft-Auen',
      title: 'Fotograf Erftstadt | Lichtraum — Schloss Gracht, Hochzeit, Portrait',
      description: 'Fotograf Erftstadt: Schloss Gracht, Erft-Auen, Herrig-Park. Hochzeiten, Portraits, Familien-Shoots. Aus Euskirchen 30 km, kostenfreie Anfahrt.',
      eyebrow: 'Fotografie · Erftstadt & Rhein-Erft',
      city: 'Erftstadt',
      tier: 3,
      targetVolume: 70,
    },
    intro: [
      'Erftstadt mit Schloss Gracht gehört zu den romantischsten Hochzeitskulissen im Rhein-Erft-Kreis — barocker Park, stille Alleen und weite Auenlandschaft. Die Erft-Auen fügen Wasser und Baumbestand hinzu.',
      'Wir fotografieren in Erftstadt Hochzeiten, Portraits und Familien-Shoots. Die Anfahrt von Euskirchen dauert etwa 30 Minuten — eine der kürzesten in unserem kostenfreien Einzugsgebiet.',
    ],
    sections: [
      { h2: 'Schloss Gracht und der Barockpark',
        body: [
          'Schloss Gracht ist ein Wasserschloss aus dem 17. Jahrhundert mit privatem Park, Orangerie, Kapelle. Mittlere Hochzeitsgröße (bis 120 Gäste), preislich moderat bis gehoben. Die Wasserspiegelung der Fassade ist ein klassischer Hochzeits-Bildtopos.',
          'Die Kastanienallee auf dem Gracht-Gelände ist eines der schönsten Portrait-Settings im gesamten Rhein-Erft-Kreis. Im Mai in voller Blüte, im Oktober goldgelb — immer fotogen.',
          'Die Kapelle im Inneren des Schlosses eignet sich für intime kirchliche Trauungen. Der Schlossinnenhof für Gruppenfotos bei Regen (überdacht).',
        ],
      },
      { h2: 'Weitere Erftstädter Kulissen',
        body: [
          'Die Erft-Auen bieten Wasserläufe, Baumalleen und Weiden. Ideal für Paar-Portraits und Familien-Shoots zur Golden Hour. Zugang über den Erft-Radweg.',
          'Der Herrig-Park im Stadtteil Liblar ist eine ruhige Park-Anlage mit Teichen und Baumbestand — weniger bekannt als Gracht, aber für kleinere Shoots mehr als ausreichend.',
          'Die historische Altstadt von Lechenich (Erftstadt-Lechenich) liefert Fachwerk-Architektur für Lifestyle-Shoots.',
        ],
      },
      { h2: 'Planung, Anfahrt, Preis-Einordnung',
        body: [
          'Mit nur 30 Minuten Anfahrtszeit ist Erftstadt eine der logistisch bequemsten Destinationen für uns. Keine versteckten Kilometerkosten, keine Stadtmaut, keine enger Parkplatzsituation wie in Köln-Innenstadt.',
          'Schloss Gracht liegt preislich moderat bis gehoben — die Saalmiete beginnt bei etwa 3.800 € für einen Samstag in der Hochsaison, Catering ist über externe Anbieter frei wählbar. Für unsere Paare ist das ein attraktives Paket: prestigeträchtige Schlosskulisse zu Preisen deutlich unter Kölner Augustusburg-Niveau.',
          'Die Erftstädter Standesämter (Lechenich, Liblar) haben kleinere Raumkapazitäten als das Stadthaus Köln, dafür oft familiärere Atmosphäre. Für standesamtliche Mikro-Hochzeiten (bis 15 Personen) eine gute Wahl.',
        ],
      },
    ],
    locations: [
      { name: 'Schloss Gracht', note: 'Wasserschloss — die Referenzlocation' },
      { name: 'Kastanienallee Schloss Gracht', note: 'blühend im Mai, golden im Oktober' },
      { name: 'Erft-Auen', note: 'Wasserläufe, Weiden, Golden Hour' },
      { name: 'Herrig-Park, Liblar', note: 'stille Park-Anlage' },
      { name: 'Altstadt Lechenich', note: 'Fachwerk-Historie' },
    ],
    faqs: [
      { q: 'Sind Hochzeiten in Schloss Gracht möglich?',
        a: 'Ja, das Schloss hat eine eigene Hochzeits-Koordination. Kapazität bis 120 Gäste. Beliebt in der Region — Samstagstermine in der Hochsaison 12 bis 18 Monate Vorlauf.' },
      { q: 'Wie weit ist Erftstadt von Euskirchen?',
        a: 'Etwa 20 km, 25 bis 30 Minuten Fahrzeit. Eine der kürzesten Anfahrten in unserem Servicegebiet.' },
      { q: 'Fotografieren Sie auch auf dem Gracht-Golfplatz?',
        a: 'Ja, mit Genehmigung. Der Golfclub hat strenge Regeln für gewerbliche Shootings, wir klären das vorab. Besonders geeignet für Business-Portraits mit Greenhintergrund.' },
      { q: 'Gibt es Alternativen zu Schloss Gracht in Erftstadt?',
        a: 'Für kleinere, intimere Hochzeiten empfehlen wir die Heimatstube Lechenich oder den privat geführten Hof Ingel. Beide weniger prestigeträchtig, aber mit echtem Lokal-Charakter.' },
      { q: 'Wie lange dauert ein typisches Familien-Shooting in der Erft-Aue?',
        a: '90 Minuten. Wir treffen uns am Erft-Radweg, etwa am Parkplatz Schwalbenhof. Von dort gehen wir etwa 20 Minuten zu einem ruhigen Plätzchen mit Baumallee, Wiese und Sicht auf den Erft-Bogen. Die Kinder spielen, wir fotografieren, niemand ist gestresst. 30 bearbeitete Fotos, Lieferung binnen 10 Werktagen. Paketpreis 290 €.' },
      { q: 'Fotografieren Sie auch Taufen und andere Familienfeiern?',
        a: 'Ja, gerne. Taufen in Erftstadt finden oft in der St.-Lambertus-Kirche in Lechenich statt — wir kennen die Abläufe und die Pfarrer:innen. Für Tauf-Reportagen bieten wir ein reduziertes Paket (2 Stunden, 60 Fotos, 390 €) an, das Zeremonie und den anschließenden Sektempfang abdeckt.' },
    ],
    closing: 'Für Erftstadt ist unsere Anfahrt besonders kurz — schreiben Sie uns gerne für Schloss Gracht, die Erft-Auen oder eine der weniger bekannten Lokationen. Wir antworten werktags innerhalb von 24 Stunden mit einem schriftlichen Angebot und zwei oder drei Terminvorschlägen. Für bestehende Kund:innen im Kreis Euskirchen oder im nahen Rhein-Erft-Umkreis bieten wir zusätzlich einen Erftstadt-Vor-Ort-Besprechungstermin in unserem Studio an, damit wir vor der eigentlichen Buchung gemeinsam klären, ob der Fotograf-Stil zum geplanten Anlass passt.',
    relatedSlugs: ['hochzeitsfotograf-koeln', 'fotograf-koeln', 'fotograf-bergheim'],
  },

  'fotograf-bergheim': {
    meta: {
      slug: 'fotograf-bergheim',
      h1: 'Fotograf in Bergheim — Paffendorfer Schloss',
      title: 'Fotograf Bergheim | Lichtraum — Paffendorfer Schloss, Portrait, Hochzeit',
      description: 'Fotograf Bergheim: Paffendorfer Schloss, Aachener Straße. Hochzeiten, Portraits, Business-Shoots. Anfahrt von Euskirchen kostenfrei.',
      eyebrow: 'Fotografie · Bergheim & Rhein-Erft',
      city: 'Bergheim',
      tier: 3,
      targetVolume: 60,
    },
    intro: [
      'Bergheim als Kreisstadt des Rhein-Erft-Kreises bietet mit dem Paffendorfer Schloss eine stille, parkartige Hochzeits- und Portrait-Kulisse — ein kleineres Barockschloss, das in den letzten Jahren zu einer unserer Standard-Locations für Mittelstand-Hochzeiten geworden ist.',
      'Wir kommen aus Euskirchen, etwa 45 Minuten Anfahrt, ohne Aufpreis.',
    ],
    sections: [
      { h2: 'Paffendorfer Schloss im Detail',
        body: [
          'Das Paffendorfer Schloss liegt am nördlichen Ende Bergheims — ein Barockschloss aus dem späten 17. Jahrhundert, umgeben von einem weitläufigen Park mit Teichen, Alleen und alten Buchen. Kapazität für Hochzeiten bis etwa 80 Gäste.',
          'Die Schloss-Innenräume sind schlicht, der Park dafür umso beeindruckender. Wir empfehlen Paffendorf-Hochzeiten vor allem für Paare, die eine ruhigere, weniger prestigeträchtige Alternative zu Schloss Augustusburg suchen. Preislich deutlich günstiger, fotografisch mindestens ebenbürtig.',
          'Für Portraits ist der Schlosspark eine unserer liebsten Kulissen: die Baumalleen filtern das Nachmittagslicht weich, die Teiche liefern Spiegelreflexionen, die Schlossfassade den formalen Rahmen.',
        ],
      },
      { h2: 'Bergheim darüber hinaus',
        body: [
          'Die Aachener Straße (historische Achse durch die Altstadt) bietet Fachwerk und kleinstädtischen Charme. Für Lifestyle-Portraits oder Business-Environmental-Shoots.',
          'Das Rhein-Erft-Zentrum ist das moderne Business-Gesicht Bergheims — Büroquartiere, Glasfassaden, urbane Architektur. Für Tech- und Dienstleistungs-Portraits angemessen.',
        ],
      },
      { h2: 'Anfahrt, Termine und Buchungsdetails',
        body: [
          'Von unserem Studio in Euskirchen fahren wir rund 45 Minuten nach Bergheim über die A61 und die L277. Im Pauschalpreis inklusive — keine versteckten Kilometerkosten.',
          'Die Hauptsaison für Paffendorf-Hochzeiten läuft von Mai bis Oktober. Samstage in der Hochsaison sind 12 bis 18 Monate vorher weg. Kurzfristige Anfragen (unter 4 Monate) decken wir bevorzugt für Freitage und Nebensaison ab.',
          'Für Bergheimer Stammkunden bieten wir einen Nachbarschaftsrabatt von 5 Prozent auf alle Folgebuchungen im gleichen Kalenderjahr (Familien-Shoots, Business-Portraits, Anlass-Fotografie). Sagen Sie das bei der zweiten Anfrage einfach dazu — wir ziehen den Rabatt automatisch vom Angebot ab.',
        ],
      },
    ],
    locations: [
      { name: 'Paffendorfer Schloss', note: 'Barockschloss mit Park — Hochzeiten bis 80 Gäste' },
      { name: 'Schlosspark Paffendorf', note: 'Baumalleen, Teiche, weiches Licht' },
      { name: 'Aachener Straße Altstadt', note: 'Fachwerk, kleinstädtisch' },
      { name: 'Rhein-Erft-Zentrum', note: 'moderne Architektur für Business-Shoots' },
    ],
    faqs: [
      { q: 'Ist Paffendorfer Schloss bei Ihnen buchbar für Hochzeiten?',
        a: 'Ja, wir fotografieren dort regelmäßig. Das Schloss hat eine externe Koordination (über den Förderverein Schloss Paffendorf), die Fotogenehmigung ist Standard.' },
      { q: 'Wie groß sollte eine Hochzeit für Paffendorf sein?',
        a: 'Ideal zwischen 30 und 80 Gästen. Darunter wirkt der Park „leer", darüber wird die Infrastruktur (Parkplätze, Toiletten, Catering-Anbindung) eng.' },
      { q: 'Unterscheidet sich eine Bergheimer Hochzeit von einer Kölner?',
        a: 'Visuell: ruhiger, weniger urban, mehr Natur-Kulisse. Preislich: meist 20 bis 30 Prozent unter Kölner Niveau bei vergleichbarer Qualität. Logistisch: kürzere Wege zwischen Trauung und Feier, oft weniger Stress für das Brautpaar.' },
      { q: 'Bieten Sie Kombi-Shootings mit benachbarten Rhein-Erft-Städten an?',
        a: 'Sehr gerne. Viele Bergheimer Paare kombinieren Schloss Paffendorf mit einem After-Wedding-Shooting auf Schloss Türnich (20 Min entfernt) oder in der Erft-Aue — zwei Locations im Paket, damit die Hochzeitsbilder mehr Bandbreite haben. Der Aufschlag liegt bei 150 €, Abstimmung der Logistik übernehmen wir.' },
      { q: 'Welche Rolle spielt das Tagebau-Umfeld fotografisch?',
        a: 'Die Braunkohle-Tagebau-Landschaft südlich von Bergheim (Richtung Hambach) ist fotografisch ein Geheimtipp für Editorial- und Paar-Shootings. Die dramatischen Horizonte und die Aussichtspunkte Sophienhöhe liefern Bildkompositionen, die im Rheinland sonst kaum zu finden sind. Für Paare mit einem Sinn für außergewöhnliche Kulissen eine empfehlenswerte Option.' },
    ],
    closing: 'Schreiben Sie uns, wenn Sie in Bergheim oder dem nördlichen Rhein-Erft-Kreis heiraten — wir kennen Paffendorf, die Tagebau-Kulisse und die umliegenden Standesämter. Auf Wunsch kombinieren wir Ihre Hochzeit mit einem After-Wedding-Shoot auf einer benachbarten Location, ohne dass Sie doppelt anreisen müssen. Für Bergheimer Unternehmen und Selbständige bieten wir zudem flexible Business-Portrait-Pauschalen an — für Kanzleien, Steuerberatungsbüros und Handwerksbetriebe, die einheitliche Team-Bilder für Website und Broschüren benötigen. Wenn Sie mit einem kleinen Startup oder einer Werbeagentur in Bergheim zusammenarbeiten, fragen Sie gerne nach unseren Startup-Paketen, die gegenüber den Standardpreisen einen deutlichen Einstiegsrabatt bieten.',
    relatedSlugs: ['hochzeitsfotograf-koeln', 'fotograf-kerpen', 'fotograf-erftstadt'],
  },

  'fotograf-kerpen': {
    meta: {
      slug: 'fotograf-kerpen',
      h1: 'Fotograf in Kerpen — Schloss Türnich & Marienfeld',
      title: 'Fotograf Kerpen | Lichtraum — Schloss Türnich, Hochzeit, Portrait',
      description: 'Fotograf Kerpen: Schloss Türnich, Marienfeld, Sindorf. Hochzeiten, Portraits, Familien-Shoots zwischen Köln und Düren.',
      eyebrow: 'Fotografie · Kerpen & Rhein-Erft',
      city: 'Kerpen',
      tier: 3,
      targetVolume: 50,
    },
    intro: [
      'Kerpen zwischen Köln und Düren bietet mit Schloss Türnich eine ruhige Park-Kulisse und mit Marienfeld eine dramatische, industrielle Alternative. Beide sind in unserem Jahreskalender feste Größen.',
      'Anfahrt aus Euskirchen etwa 35 Minuten über A61.',
    ],
    sections: [
      { h2: 'Schloss Türnich — barock und introspektiv',
        body: [
          'Schloss Türnich ist ein barockes Wasserschloss mit weitem Park, Kapelle und Orangerie. Kapazität für mittlere Hochzeiten bis etwa 100 Gäste. Die Parkanlage ist für Portrait-Shootings ein kleines Paradies: stille Alleen, eine Ehreninsel im Schlossgraben, alte Baumbestände.',
          'Der Park ist gleichzeitig eine ökologische Demeter-Wirtschaft. Das bedeutet: keine Pestizide, Wildblumen statt steriler Rasen, Bienen und Vögel. Für Fotografien gibt das eine natürliche Lebendigkeit, die formellere Schlossparks verloren haben.',
        ],
      },
      { h2: 'Marienfeld — industrielle Alternative',
        body: [
          'Das ehemalige Festivalgelände bei Marienfeld (zwischen Kerpen und Grevenbroich) hat eine dramatische, industrielle Ästhetik. Für Editorial-Paar-Shoots und Lifestyle-Portraits eine unterschätzte Kulisse — weite Flächen, industrielle Silhouetten, klare Horizonte.',
          'Wir empfehlen Marienfeld für Paare, die eine moderne Ästhetik jenseits der klassischen Schlossromantik suchen.',
        ],
      },
      { h2: 'Kerpen als Hochzeits- und Portrait-Region',
        body: [
          'Kerpen ist oft der unterschätzte Teil des Rhein-Erft-Kreises. Mit knapp 70.000 Einwohnern ist es zwar klein, aber mit Schloss Türnich, dem Marienfeld und dem Stadtteil Sindorf drei sehr unterschiedliche Gesichter. Für Paare, die Köln-Nähe mit Burgen-Feeling kombinieren wollen, bietet Kerpen mehr, als die Google-Suche vermuten lässt.',
          'Unsere Anfahrt aus Euskirchen dauert etwa 35 Minuten über die A61 und die B264. Die Strecke ist tagsüber entspannt, zu Berufsverkehrszeiten etwas länger. Wir planen Hochzeitsanfahrten grundsätzlich mit 15 Minuten Puffer.',
          'Schloss Türnich hat eine einzigartige Demeter-Philosophie: der Park wird biologisch-dynamisch bewirtschaftet, die Wildblumen-Wiesen sind unterm Jahr immer lebendig, und das Schloss selbst vermittelt eine Ruhe, die formeller bewirtschaftete Park-Anlagen oft verloren haben. Für Paare mit Sinn für ökologische Nachhaltigkeit ist das ein zusätzlicher Argument.',
        ],
      },
    ],
    locations: [
      { name: 'Schloss Türnich', note: 'Barockschloss mit Demeter-Park' },
      { name: 'Marienfeld Festivalgelände', note: 'Industriekulisse, Editorial' },
      { name: 'Sindorf', note: 'ländlicher Kerpen-Stadtteil' },
    ],
    faqs: [
      { q: 'Ist Schloss Türnich wirklich ein Demeter-Betrieb?',
        a: 'Ja, die Park- und Gartenanlage wird biologisch-dynamisch bewirtschaftet. Das ist fotografisch kein Hindernis, sondern ein Gewinn — die Wildblumen-Wiesen sehen lebendiger aus als sterile Parks.' },
      { q: 'Kann man auf dem Marienfeld-Festivalgelände fotografieren?',
        a: 'Ja, mit Genehmigung des Eigentümers. Wir klären das vorab. Die Genehmigung ist typischerweise unkompliziert und kostenfrei für private Portrait- und Hochzeitsshootings.' },
      { q: 'Ist Kerpen für Hochzeiten weniger beliebt als Bergisch Gladbach?',
        a: 'Ja, Kerpen ist deutlich weniger bekannt als Bergisch Gladbach oder Brühl. Das hat Vorteile: weniger Konkurrenz um Samstagstermine, niedrigere Schloss-Mietpreise, ruhigere Trauungsorte. Wer Schloss Türnich als Location hat, bekommt eine bessere Hochzeit für weniger Geld.' },
      { q: 'Welche Jahreszeit passt am besten zu Schloss Türnich?',
        a: 'Spätsommer und früher Herbst (September bis Mitte Oktober) sind unsere Empfehlung. Die Wildblumen-Wiesen blühen dann in einer warm-bronzen Palette, das Licht ist weich, die Demeter-Plantagen sind in voller Vitalität. Mai und Juni sind ebenfalls gut, aber dann dominieren die frischen Grüntöne, die bei manchen Hochzeitspaaren weniger gewünscht sind als das spätsommerliche Gold.' },
      { q: 'Eignet sich Marienfeld auch für Business-Portraits?',
        a: 'Eingeschränkt. Der industrielle Charakter des ehemaligen Festivalgeländes kann für spezifische Branchen (Tech, Architektur, kreative Dienstleistungen) sehr passend sein. Für klassische Corporate-Portraits (Kanzlei, Bank, Versicherung) wirkt die Kulisse zu avantgardistisch. Wir beraten vorab, ob Marienfeld zu Ihrer Zielgruppe passt.' },
    ],
    closing: 'Für Kerpen-Shootings — schreiben Sie uns. Schloss Türnich und Marienfeld kennen wir genau, und wir helfen Ihnen gern dabei, zwischen der klassischen Barock-Kulisse und der modernen Industrieästhetik die passende Variante für Ihren Anlass zu wählen. Für Kerpener Stammkunden bieten wir zudem schnelle Termin-Verfügbarkeiten an, oft innerhalb von zwei bis drei Wochen nach Anfrage — gerade für Bewerbungsfotos, Portrait-Auffrischungen oder Baby-Shoots ist das ein spürbarer Vorteil gegenüber Kölner Studios mit wochenlangen Wartelisten. Wer bereits einmal bei uns fotografiert hat und nun für Familie, Team oder Unternehmen ein Folgeshooting plant, wird automatisch in unsere Stammkunden-Priorität aufgenommen.',
    relatedSlugs: ['fotograf-bergheim', 'fotograf-huerth', 'hochzeitsfotograf-koeln'],
  },

  'fotograf-huerth': {
    meta: {
      slug: 'fotograf-huerth',
      h1: 'Fotograf in Hürth — Ville-Park & Knapsack',
      title: 'Fotograf Hürth | Lichtraum — Ville-Park, Portrait, Business',
      description: 'Fotograf Hürth: Ville-Park, Knapsack-Industriekulisse, Hermülheim. Portraits, Business-Shoots, Hochzeiten. Aus Euskirchen schnell erreichbar.',
      eyebrow: 'Fotografie · Hürth & Rhein-Erft',
      city: 'Hürth',
      tier: 3,
      targetVolume: 50,
    },
    intro: [
      'Hürth als Medien-Stadt Kölns bietet den Ville-Park und die beeindruckende Industriekulisse Knapsack für editoriale Shootings mit Charakter. Mit Bavaria Filmstudios und der Medienbranche allgemein hat Hürth zudem eine auffallend hohe Dichte an Business- und Editorial-Kunden.',
      'Anfahrt aus Euskirchen etwa 40 Minuten.',
    ],
    sections: [
      { h2: 'Ville-Park und Knapsack',
        body: [
          'Der Ville-Park ist eine der schönsten grünen Flächen im Rhein-Erft-Kreis — breite Rasenflächen, Seerosenteiche, alte Baumgruppen. Für Familien- und Paar-Shootings ideal, da weitläufig und wenig frequentiert.',
          'Die Industriekulisse Knapsack (Chempark-Verbund) ist eine der dramatischsten Industriefassaden im Rheinland. Für Editorial- und Lifestyle-Portraits eine unerreichte Kulisse — wir fotografieren dort nur mit ausdrücklicher Einzelgenehmigung, die wir pro Projekt abstimmen.',
        ],
      },
      { h2: 'Hermülheim und Medienkunden',
        body: [
          'Hermülheim ist der historische Kern Hürths. Für Lifestyle-Portraits mit kleinstädtischem Charme gut geeignet.',
          'Media- und Businesskunden in Hürth (Bavaria, RTL, Studio-Betriebe) buchen bei uns oft Onsite-Portrait-Sessions direkt in den Studios. Für diese Kunden bieten wir pauschale Team-Packages ab 4 Personen mit 79 € pro Person an.',
        ],
      },
      { h2: 'Warum Hürth fotografisch interessant ist',
        body: [
          'Hürth hat einen Ruf als Medien-Stadt und als Chempark-Nachbar. Beides ist fotografisch nützlich: die Medien-Infrastruktur bringt uns regelmäßig Business- und Personal-Branding-Kunden aus der Fernseh- und Produktionsbranche, die Chempark-Kulisse erlaubt industrielle Editorial-Shoots mit echtem Charakter.',
          'Gleichzeitig ist Hürth überraschend grün. Der Ville-Park, die Ville-Seen und die umliegenden Wälder bilden einen naturnahen Kontrast zur Industrie. Für Familien-Shoots und ruhigere Paar-Portraits ist Hürth daher vielfältiger, als die Google-Suche vermuten lässt.',
          'Anfahrt von Euskirchen: etwa 40 Minuten über die A61 und die L497. Für Termine in der Bavaria oder im Chempark rechnen wir vor allem morgens mehr Zeit ein, weil der Zubringer zum Chempark zu Schichtwechseln stark befahren ist.',
        ],
      },
    ],
    locations: [
      { name: 'Ville-Park', note: 'weitläufiger Stadtpark — Familien, Paare' },
      { name: 'Knapsack Industriekulisse', note: 'Editorial-Kulisse mit Genehmigung' },
      { name: 'Hermülheim Altstadt', note: 'kleinstädtischer Charme' },
    ],
    faqs: [
      { q: 'Fotografieren Sie in den Bavaria Filmstudios?',
        a: 'Ja, wir haben mehrere Kunden mit Bavaria-Bezug und kommen regelmäßig zu Onsite-Portrait-Terminen ins Studio. Die Zutrittsgenehmigung regelt normalerweise unsere auftragstellende Firma.' },
      { q: 'Kann ich in der Knapsack-Industriekulisse privat fotografieren lassen?',
        a: 'Das ist grundsätzlich möglich, aber nicht unkompliziert. Knapsack ist aktives Industriegelände mit Sicherheitsauflagen. Wir haben eine Basis-Vereinbarung mit dem Standortbetreiber, müssen aber pro Shooting eine Einzelgenehmigung einholen. Vorlauf 2 bis 3 Wochen.' },
      { q: 'Gibt es Hochzeitslocations in Hürth?',
        a: 'Weniger als in Brühl oder Bergheim, aber der Ville-Park eignet sich für Paar-Portraits im Rahmen einer Kölner oder Brühler Hochzeit. Eine komplette Hochzeitslocation in Hürth ist uns nicht bekannt.' },
      { q: 'Wie gehen Sie mit der Industriegeschichte Hürths um?',
        a: 'Industriearchitektur ist für uns fotografisch eine Bereicherung, keine Belastung. Die Knapsack-Silhouette, die Ville-Seen als renaturiertes Tagebaugebiet, das Chempark-Areal — alles sind Kulissen mit Charakter. Wir wählen sie nur bei Kund:innen, deren Ästhetik dazu passt. Bei klassischen Portrait-Shoots halten wir uns an die ruhigen Park-Locations.' },
      { q: 'Sind die Ville-Seen öffentlich zugänglich für Shootings?',
        a: 'Ja, alle sechs Ville-Seen sind frei zugänglich. Die Otto-Maigler-Seen und der Gleuel sind besonders ruhig und bieten Wasser-Spiegelungen für Portrait-Shoots. Im Sommer sind die Seen allerdings gut besucht — wir planen Shootings dort grundsätzlich für Vormittagstermine oder für Wochentage.' },
    ],
    closing: 'Für Hürth-Shoots — Ville-Park, Knapsack oder Media-Industrie — schreiben Sie uns. Wir bringen die Kulissen-Kenntnis mit und finden mit Ihnen zusammen das richtige Setting — ob Sie Natur, Industrie oder Medien-Hintergründe bevorzugen. Für Bavaria-Mitarbeiter:innen, Producer:innen und freie Regie-Kolleg:innen bieten wir gesonderte Schnellbuchungs-Slots für Headshot-Erneuerungen und Personal-Branding-Pakete an, die auf die oft kurzfristige Planung in der Medienbranche Rücksicht nehmen. Bei Onsite-Shoots im Bavaria-Studio kommen wir mit mobiler Technik inklusive mobiler Softboxen zu Ihnen. Auch für Kunden aus benachbarten Berufsfeldern — Synchronsprecher:innen, Texter:innen, freie Produktions-Koordinator:innen — ist Hürth logistisch ideal, weil wir innerhalb weniger Tage reagieren können, was Kölner Studios in der Regel nicht mehr leisten.',
    relatedSlugs: ['fotograf-bruehl', 'fotograf-koeln', 'businessfotograf-koeln'],
  },

  'fotograf-bruehl': {
    meta: {
      slug: 'fotograf-bruehl',
      h1: 'Fotograf in Brühl — Schloss Augustusburg UNESCO-Welterbe',
      title: 'Fotograf Brühl | Lichtraum — Schloss Augustusburg, Hochzeit, Portrait',
      description: 'Fotograf Brühl: Schloss Augustusburg (UNESCO-Welterbe), Schlosspark, Max-Ernst-Museum. Hochzeiten, Portraits, Business-Shoots.',
      eyebrow: 'Fotografie · Brühl & UNESCO-Welterbe',
      city: 'Brühl',
      tier: 3,
      targetVolume: 50,
    },
    intro: [
      'Brühl mit Schloss Augustusburg (UNESCO-Welterbe) gehört zu den prestigeträchtigsten Hochzeitslocations Deutschlands — barocke Architektur, Alleen, ein weitläufiger Schlosspark. Für Hochzeitsfotografie im Rheinland eine Referenzadresse.',
      'Anfahrt aus Euskirchen etwa 30 Minuten.',
    ],
    sections: [
      { h2: 'Schloss Augustusburg — der Klassiker',
        body: [
          'Schloss Augustusburg ist das barocke Vorzeigeschloss der Region. Fassade, Prunktreppe, englischer Park mit Wasseranlagen, direkte Nachbarschaft zu Schloss Falkenlust. Kapazität für Hochzeiten 40 bis 180 Gäste.',
          'Für Fotograf:innen: fast jedes Licht funktioniert. Der Park hat gefilterte Nachmittagssonnen, die Fassade liefert dramatischen Hintergrund, die Treppe eignet sich für Gruppenfotos bis 60 Personen ohne Staffelei.',
          'Preisklasse gehoben: Saal-Miete 3.500 bis 8.000 €, je nach Saison. Beliebt — 18 Monate Vorlauf bei Samstagen in der Hochsaison keine Seltenheit.',
        ],
      },
      { h2: 'Weitere Brühler Locations',
        body: [
          'Schloss Falkenlust ist das kleinere Jagdschloss 15 Minuten Fußweg von Augustusburg — ideal für After-Wedding-Shoots oder für kleinere standesamtliche Trauungen mit Portrait-Anschluss im barocken Park.',
          'Das Max-Ernst-Museum bietet modernen architektonischen Kontrast zu den Schlössern. Für Editorial- und Business-Portraits eine interessante urbane Kulisse.',
          'Der Schlosspark Brühl (öffentlich zugänglich) ist zudem für Familien-Shoots sehr empfehlenswert — weitläufig, ruhig, mit vielen Bildmotiven.',
        ],
      },
      { h2: 'Anfahrt, Parkplätze, Infrastruktur',
        body: [
          'Von Euskirchen fahren wir über die A61 in etwa 30 Minuten nach Brühl. Die kurze Anfahrt macht Brühl für uns zu einer der logistisch einfachsten Hochzeits-Locations im Kreis.',
          'Parken im Schloss Augustusburg: für Hochzeiten gibt es ein kleines reserviertes Kontingent im Schlossparkhaus. Für Gäste reichen die öffentlichen Parkplätze am Rondell meist aus. Wir empfehlen Brautpaaren, bei der Buchung einen reservierten Brautauto-Stellplatz direkt vor dem Ehrenhof mitzubuchen — das ist nicht Standard, aber auf Nachfrage möglich.',
          'Die Brühler Gastronomie rund um die Schlösser ist vielfältig. Für kleinere Feiern funktioniert das Schlosshotel Max-Ernst, für größere Bankette muss ins nahe Köln oder nach Bonn verlagert werden. Die meisten Brühler Paare entscheiden sich für das Catering direkt im Schloss.',
        ],
      },
    ],
    locations: [
      { name: 'Schloss Augustusburg (UNESCO)', note: 'Barock-Vorzeige-Schloss' },
      { name: 'Schlosspark Brühl', note: 'öffentlich zugänglich, weitläufig' },
      { name: 'Schloss Falkenlust', note: 'kleineres Jagdschloss — intim' },
      { name: 'Max-Ernst-Museum', note: 'modern, editorial' },
    ],
    faqs: [
      { q: 'Kann ich in Schloss Augustusburg heiraten?',
        a: 'Ja, das Schloss hat mehrere Hochzeits-Koordinator:innen und unterschiedliche Saal-Optionen (Gelber Saal, Musiksaal, Grüner Saal). Kapazität bis 180. Wegen Welterbestatus strenge Regeln für Fotografen und Dekoration.' },
      { q: 'Wie früh muss man Augustusburg buchen?',
        a: 'Für Samstage zwischen Mai und September 18 Monate Vorlauf, manchmal mehr. Werktag und Nebensaison oft noch 6 bis 9 Monate vorher möglich.' },
      { q: 'Gibt es auch günstigere Alternativen in Brühl?',
        a: 'Ja, der Schlosspark ist kostenlos zugänglich — wir fotografieren dort auch Paare, die nicht in Augustusburg selbst heiraten, sondern die Schloss-Kulisse „nur" für Portraits nutzen möchten. Eine elegante, günstigere Variante.' },
      { q: 'Gibt es Fotografen-Einschränkungen in Augustusburg?',
        a: 'Ja. Kein Blitzlicht im Inneren, keine Stativnutzung in bestimmten Sälen, keine kommerziellen Aufnahmen ohne Genehmigung. Wir kennen die Regeln und arbeiten entsprechend.' },
      { q: 'Wie wirkt sich das UNESCO-Welterbestatus auf Hochzeiten aus?',
        a: 'Praktisch: höhere Saalmieten, strengere Dekorationsregeln (keine Kerzen, keine Blumenarrangements an den Wänden), enger vorgegebene Zeremonieabläufe. Fotografisch: ein Prestige, der international wirkt. Für Paare mit internationalem Familiennetzwerk ist der UNESCO-Status ein echter Mehrwert, der die höheren Kosten rechtfertigt.' },
      { q: 'Kann ich Schloss Falkenlust separat für ein Shooting buchen?',
        a: 'Ja, Schloss Falkenlust ist auch einzeln zugänglich — sowohl als Hochzeits-Trauungsort (für kleinere Zeremonien bis 30 Personen) als auch als Portrait-Location für Paar- oder Einzelshootings. Die Buchung läuft über das Fachdezernat der UNESCO-Schlösser-Verwaltung.' },
    ],
    closing: 'Für Brühl-Shoots — Augustusburg, Falkenlust oder Max-Ernst-Museum — schreiben Sie uns. Wir kennen die UNESCO-Auflagen und halten sie ein. Auf Wunsch organisieren wir im Vorfeld ein kurzes Location-Briefing, in dem wir gemeinsam mit Ihnen die Räume besichtigen und die besten Portrait-Positionen markieren. Für Brühler Paare mit kürzerem Planungsvorlauf haben wir eine abgespeckte Augustusburg-Variante im Angebot, die ohne Schloss-Innen-Shooting auskommt und stattdessen auf Parkanlagen, Falkenlust und die zugängliche Außenfassade setzt — so bleibt das UNESCO-Ambiente erhalten, ohne dass komplizierte Raumgenehmigungen nötig werden.',
    relatedSlugs: ['hochzeitsfotograf-koeln', 'fotograf-huerth', 'fotograf-erftstadt'],
  },

  'fotograf-pulheim': {
    meta: {
      slug: 'fotograf-pulheim',
      h1: 'Fotograf in Pulheim — Abtei Brauweiler',
      title: 'Fotograf Pulheim | Lichtraum — Abtei Brauweiler, Hochzeit, Portrait',
      description: 'Fotograf Pulheim: Abtei Brauweiler (romanisches Kloster), Stommeln, Dansweiler. Hochzeiten, Portraits, Familien-Shoots.',
      eyebrow: 'Fotografie · Pulheim & Köln-Nord',
      city: 'Pulheim',
      tier: 3,
      targetVolume: 40,
    },
    intro: [
      'Pulheim nördlich von Köln beherbergt die Abtei Brauweiler — ein ehemaliges Benediktinerkloster mit romanischer Architektur und weitem Park, ideal für stimmungsvolle Hochzeitsreportagen.',
      'Anfahrt aus Euskirchen etwa 50 Minuten.',
    ],
    sections: [
      { h2: 'Abtei Brauweiler im Detail',
        body: [
          'Die Abtei Brauweiler ist eines der wichtigsten romanischen Kulturdenkmäler im Rheinland. Ehemaliges Benediktinerkloster, heute Kultur- und Kongresszentrum. Für Hochzeiten bieten sich der Kreuzgang, der Innenhof und die romanische Basilika an.',
          'Der Kreuzgang ist unter Fotograf:innen ein Insider-Tipp: gleichmäßiges Nordlicht, Steinsäulen-Raster, Schatten-Licht-Kontraste wie in einem Renaissance-Gemälde. Für Portrait-Shoots im Rahmen von Hochzeiten eine Bank.',
          'Die Basilika erlaubt kirchliche Trauungen (nach Absprache mit der Gemeinde) oder standesamtliche im angrenzenden Raum.',
        ],
      },
      { h2: 'Pulheim-Orte jenseits der Abtei',
        body: [
          'Stommeln und Dansweiler sind ländlich-ruhige Ortsteile Pulheims mit Fachwerk-Architektur und weiten Feldern. Für Familien- und Paar-Shootings mit ländlichem Charakter.',
        ],
      },
      { h2: 'Warum Pulheim als Hochzeitsort funktioniert',
        body: [
          'Pulheim liegt direkt an der Grenze zu Köln-Nord, ist aber deutlich günstiger und ruhiger als die Stadtteile im Kölner Stadtgebiet. Das macht die Abtei Brauweiler zu einer attraktiven Alternative zu den teureren und stark frequentierten Kölner Schlössern: Prestige-Kulisse, romanische Architektur, barocker Park — zu einem Drittel der Preise, die für vergleichbare Kölner Locations aufgerufen werden.',
          'Die Abtei ist zudem ein ernstzunehmender Hochzeitsort in der regionalen Presse. Für Paare, die eine prestigeträchtige Location suchen, aber dem Kölner Augustusburg-Trubel aus dem Weg gehen wollen, ist Brauweiler die bessere Wahl. Die Hochzeits-Kommission der Abtei ist professionell und unkompliziert.',
          'Logistisch: aus Euskirchen fahren wir etwa 50 Minuten über die A61, die Kölner Umgehung und die L183. Bei Hochzeiten empfehlen wir eine Anfahrt an den Vorabend mit Übernachtung in einem der Pulheimer oder Köln-Chorweiler Hotels.',
        ],
      },
    ],
    locations: [
      { name: 'Abtei Brauweiler', note: 'romanisches Kloster — Hochzeiten, Portraits' },
      { name: 'Kreuzgang Brauweiler', note: 'Geheim-Tipp für Portrait-Shoots' },
      { name: 'Stommeln', note: 'ländlich, Fachwerk' },
      { name: 'Dansweiler', note: 'weite Feldlandschaft' },
    ],
    faqs: [
      { q: 'Ist die Abtei Brauweiler für Hochzeiten buchbar?',
        a: 'Ja, die Abtei ist ein etablierter Hochzeitsort. Kapazität im Kreuzgang etwa 80 bis 120 Personen, in der Basilika bis 200. Buchung über das LVR-Kulturzentrum.' },
      { q: 'Gibt es Einschränkungen für Fotografen im Kreuzgang?',
        a: 'Kein Blitzlicht, keine Stative (außer für offizielle Gruppenfotos), keine Dekoration an den Steinsäulen. Wir halten uns an diese Regeln und haben sie im Repertoire.' },
      { q: 'Wie weit ist Pulheim von Köln?',
        a: 'Pulheim grenzt direkt an Köln-Nord. Die Abtei ist etwa 15 km vom Kölner Dom entfernt, etwa 50 km von Euskirchen.' },
      { q: 'Welche Hochzeitsgrößen eignen sich für die Abtei Brauweiler?',
        a: 'Die Abtei ist flexibel: kleine standesamtliche Trauungen im Kreuzgang-Saal (20 bis 50 Gäste), mittlere Trauungen in der romanischen Basilika (bis 120 Gäste) oder größere Feiern im Kulturzentrum mit angeschlossenen Banketträumen (bis 200 Gäste). Wir kennen die unterschiedlichen Setups und planen die Reportage entsprechend.' },
      { q: 'Fotografieren Sie auch Tauf- und Firmungsreportagen in Brauweiler?',
        a: 'Ja, die Klosterkirche ist für Tauf- und Firmungsfeiern eine atmosphärisch außergewöhnliche Wahl. Wir bieten für kirchliche Sakramente abgestufte Pakete an: eine Tauf-Reportage (2 Stunden, 60 bearbeitete Fotos, 390 €) und eine Firmungs-Reportage mit anschließendem Familien-Shoot (3 Stunden, 80 Fotos, 490 €).' },
      { q: 'Wie groß ist der Kreuzgang genau?',
        a: 'Etwa 35 × 35 Meter mit überdachten Arkaden und einem Innenhof mit Garten. Fotografisch bedeutet das: für Einzelportraits und Paar-Shoots hervorragend, für große Gruppenfotos (über 40 Personen) zu eng. Für Gruppenfotos weichen wir auf den Park vor der Basilika aus.' },
    ],
    closing: 'Für Pulheim- und Abtei-Brauweiler-Shoots — schreiben Sie uns. Die Kloster-Fotografie beherrschen wir und kennen die Raumakustik, die Lichtverhältnisse und die liturgischen Abläufe, die für eine stimmige Reportage wichtig sind. Für Brauweiler-Paare bieten wir zusätzlich eine kostenlose Vorab-Besichtigung der Klosterräume an: wir gehen mit Ihnen den Kreuzgang, die Basilika und die Konferenzräume durch und markieren gemeinsam die besten Portrait-Spots, Gruppenfoto-Positionen und möglichen Backup-Locations bei Regen — so kommen Sie am Hochzeitstag entspannt und gut vorbereitet an.',
    relatedSlugs: ['hochzeitsfotograf-koeln', 'fotograf-koeln', 'fotograf-bergheim'],
  },

  'fotograf-weilerswist': {
    meta: {
      slug: 'fotograf-weilerswist',
      h1: 'Fotograf in Weilerswist — unser Zuhause',
      title: 'Fotograf Weilerswist | Lichtraum — Portrait, Hochzeit, Familie',
      description: 'Fotograf Weilerswist: Burg Metternich, Erft-Auen, Schloss Loersfeld. Portraits, Hochzeiten, Familien-Shoots in unserer Heimatgemeinde.',
      eyebrow: 'Fotografie · Weilerswist · Unsere Homebase',
      city: 'Weilerswist',
      tier: 3,
      targetVolume: 20,
    },
    intro: [
      'Weilerswist ist unser Zuhause. Zwischen Euskirchen und Köln, direkt an der A1, liegt der Ort, in dem wir unser Studio aufgeschlagen haben — wir kennen jede Ecke persönlich, weil wir hier leben. Das macht Weilerswist für uns besonders: keine Fahrtzeit, keine Anreisestress, und für Sie als Kund:in gilt Privatheit statt Dauerrummel einer Großstadt.',
      'Wir fotografieren in Weilerswist Hochzeiten, Paare, Familien, Portraits und Business-Shoots — in der Regel outdoor in der Erft-Aue, auf Schloss Loersfeld oder vor der Burg Metternich, fallweise auch direkt bei Ihnen zu Hause im Ortskern.',
    ],
    sections: [
      { h2: 'Warum gerade Weilerswist für ein Shooting?',
        body: [
          'Weilerswist hat eine Besonderheit, die viele Besucher nicht auf Anhieb sehen: die Erft-Auen. Der Fluss schlängelt sich in weiten Bögen durch Feldlandschaft, flankiert von Baumalleen und kleinen Brücken. Zur Golden Hour im Spätsommer ist der Erft-Radweg zwischen Schwerfen und Müggenhausen eine der schönsten Landschafts-Kulissen im Rheinland.',
          'Die Burg Metternich ist eine kleine Wasserburg am Rand des Ortes — klein genug, dass man sie in zehn Minuten umrundet, aber groß genug für stimmungsvolle Hochzeits- und Paar-Portraits. Nicht berühmt wie Satzvey, nicht prestigeträchtig wie Gracht — aber genau deswegen still und privat.',
          'Schloss Loersfeld (direkt an der Grenze zu Kerpen) gehört formal zu Weilerswist. Barockes Kleinod mit Park, für Mikro-Hochzeiten (bis 50 Gäste) eine fast perfekte Alternative zu den bekannteren Regionalschlössern.',
        ],
      },
      { h2: 'Für unsere Nachbar:innen',
        body: [
          'Weilerswister Familien bekommen bei uns einen kleinen Stammkunden-Vorteil: schnellere Terminverfügbarkeit, Shootings bei Ihnen im Garten, günstigere Mini-Packages für Geburtstag- oder Weihnachts-Portraits.',
          'Wer in Weilerswist, Lommersum oder Metternich heiratet, bekommt von uns eine besondere Einordnung: kürzeste Anfahrtszeit, genaue Kenntnis der Standesämter (das Weilerswister Standesamt ist klein, familiär, hat eigene Abläufe), und oft auch persönliche Empfehlungen für Catering, Blumen und Musik.',
          'Für Business- und Bewerbungs-Portraits sind Weilerswister besonders schnell bedient: der Weg zum Studio in Euskirchen ist 10 Minuten, oft reicht ein spontaner Vormittagstermin.',
        ],
      },
      { h2: 'Weilerswister Kulissen im Einzelnen',
        body: [
          'Burg Metternich: Wasserburg mit kleinem Park. Hochzeits-Trauungen vor der Burg sind mit Genehmigung möglich. Für Paar-Portraits eine ruhige Alternative zu Kölner und Euskirchener Großlocations.',
          'Erft-Auen: der Bereich zwischen Erftbrücke und Müggenhausen. Weites Feld, Baumalleen, Erft-Schleife. Ideal für Familien-Shootings zur Golden Hour.',
          'Schloss Loersfeld: direkt an der Grenze zu Kerpen, aber geografisch Weilerswister. Barockes Kleinod, privat geführt. Für intime Hochzeiten bis 50 Gäste.',
          'Der alte Weilerswister Ortskern mit der katholischen Pfarrkirche St. Kunibert und dem historischen Rathaus-Platz: urbane kleine Kulisse für Lifestyle-Portraits.',
          'Der Naturpark Eifel beginnt direkt südlich unserer Ortsgrenzen — für After-Wedding-Shootings in Wäldern und auf Heidewiesen ist die Anfahrt minimal. Wir kennen jede Sichtachse am Kuckesberg und an der Erftquelle.',
        ],
      },
      { h2: 'Warum Weilerswist als Standort für unser Studio funktioniert',
        body: [
          'Als wir vor Jahren unser Studio in Weilerswist ankommen ließen, war das kein zufälliger Ort. Die Lage zwischen Euskirchen, Köln und Bonn ist fotografisch ideal: wir erreichen alle drei Metropolen in unter 45 Minuten, ohne in einem der drei zu wohnen. Das gibt uns eine „äußere" Perspektive auf jede der drei Städte und erlaubt, sie mit frischem Blick zu fotografieren.',
          'Für unsere Weilerswister Kund:innen bedeutet das konkret: Sie bekommen einen Fotografen, der auf Augenhöhe arbeitet, keine Dienstleister-Attitüde mitbringt und echte Regionalkenntnisse hat. Wir sind Ihre Nachbarn, nicht fern-dienstleistende Kölner Studio-Marke.',
        ],
      },
    ],
    locations: [
      { name: 'Burg Metternich', note: 'kleine Wasserburg — intim, privat' },
      { name: 'Erft-Auen (Erft-Radweg)', note: 'Feldlandschaft, Baumalleen' },
      { name: 'Schloss Loersfeld', note: 'Barockschloss, Mikro-Hochzeiten' },
      { name: 'Weilerswister Ortskern', note: 'Pfarrkirche, Rathaus-Platz' },
    ],
    faqs: [
      { q: 'Wie weit ist Ihr Studio von Weilerswist entfernt?',
        a: 'Unser Studio liegt in Euskirchen, etwa 10 km und 15 Minuten von Weilerswist. Damit sind wir für Weilerswister der am nächsten gelegene Fotograf im Kreis.' },
      { q: 'Bieten Sie Stammkunden-Konditionen für Weilerswister an?',
        a: 'Ja. Familien, die mehrere Shootings mit uns machen (Schwangerschaft, Neugeborenes, Familien-Jahresbilder), bekommen eine abgestufte Preisstruktur mit Stammkunden-Rabatt. Sagen Sie uns einfach beim zweiten Termin Bescheid.' },
      { q: 'Kennen Sie das Weilerswister Standesamt?',
        a: 'Ja, persönlich. Das Weilerswister Standesamt ist klein und hat eigene Abläufe — wir wissen, wo wir bei der Zeremonie stehen dürfen und kennen die Standesbeamtin.' },
      { q: 'Kommen Sie für spontane Familien-Shoots nach Hause?',
        a: 'Sehr gerne. In Weilerswist können wir oft innerhalb von 2 bis 3 Tagen Verfügbarkeit für ein 60- bis 90-Minuten-Familienshooting bei Ihnen zu Hause, im Garten oder in der Erft-Aue organisieren.' },
    ],
    closing: 'Wenn Sie in Weilerswist wohnen — schreiben Sie uns einfach. Wir sind die Fotograf:innen um die Ecke, und das hat Vorteile, die Sie bei einem Kölner oder Bonner Studio nicht finden.',
    relatedSlugs: ['hochzeitsfotograf-euskirchen', 'bewerbungsfotos-euskirchen', 'fotograf-koeln'],
  },
}

export const cityPageSlugs = Object.keys(cityPages)
